### ISSUE TITLE
unable to add pulp_rpmrepo (undefined method `each' for nil:NilClass)

### ISSUE THREAD

**Issue by TJM** [Katello/puppet-pulp#245]
We created our pulp server today and tried to use the pulp_rpmrepo provider to configure it, but it is getting the following error: (end of puppet agent -t --debug)

```
Debug: Prefetching api resources for pulp_rpmrepo
Debug: Storing state
Debug: Stored state in 0.05 seconds
Error: Failed to apply catalog: undefined method `each' for nil:NilClass
Debug: Dynamically-bound server lookup failed, falling back to report_server setting
Debug: Dynamically-bound port lookup failed; falling back to report_port setting
Debug: Using cached connection for https://mbi-foreman-01.utmb.lan:8140
Debug: Caching connection for https://mbi-foreman-01.utmb.lan:8140
Debug: Closing connection for https://mbi-foreman-01.utmb.lan:8140
```

Here is the relevant data:

```
---
pulp::debugging_mode: true
pulp::log_level: DEBUG
pulp::ssl_verify_client: optional
pulp::https_cert: /etc/puppetlabs/puppet/ssl/certs/%{::fqdn}.pem
pulp::https_key: /etc/puppetlabs/puppet/ssl/private_keys/%{::fqdn}.pem
pulp::https_chain: /etc/puppetlabs/puppet/ssl/certs/ca.pem
pulp::admin::verify_ssl: false
pulp::admin::logging_filename: /var/log/pulp/admin.log
pulp::admin::logging_call_log_filename: /var/log/pulp/server_calls.log

profile::pulp::rpmrepos:
  centos-7-x86_64-base:
    display_name: CentOS 7 x86_64 Base
    feed: http://mirror.centos.org/centos/7/os/x86_64/
    relative_url: centos/7/os/x86_64/
    remove_missing: true
    retain_old_count: 2
    serve_http: true
    serve_https: true
    validate: true
  centos-7-x86_64-updates:
    display_name: CentOS 7 x86_64 Updates
    feed: http://mirror.centos.org/centos/7/updates/x86_64/
    relative_url: centos/7/updates/x86_64/
    remove_missing: true
    retain_old_count: 2
    serve_http: true
    serve_https: true
    validate: true
  centos-7-x86_64-epel:
    display_name: CentOS 7 x86_64 EPEL
    feed: http://download.fedoraproject.org/pub/epel/7/x86_64/
    relative_url: epel/7/x86_64/
    remove_missing: true
    retain_old_count: 2
    serve_http: true
    serve_https: true
    validate: true
```

Here is the profile/manifests/pulp.pp:

```
class profile::pulp (
  $rpmrepos = {},
) {

# Repo: You will have to use upstream until pulp is online, then it can point to itself
#  include ::repos::pulp2
  include ::pulp::repo::upstream

  include ::apache
  include ::apache::mod::proxy
  include ::apache::mod::headers

  include ::pulp
  include ::pulp::admin

  # RPM Repos
  create_resources('pulp_rpmrepo', $rpmrepos)

  firewall { '100 INPUT allow http(s) from all':
    dport  => [ '80', '443' ],
    proto  => 'tcp',
    action => 'accept',
    chain  => 'INPUT',
  }

  firewall { '100 INPUT allow http(s) from all IPv6':
    dport    => [ '80', '443' ],
    proto    => 'tcp',
    action   => 'accept',
    chain    => 'INPUT',
    provider => 'ip6tables',
  }
}
```

In addition, I had to SSH in and run `pulp-admin login -u admin` using the "default_password" to populate /root/.pulp/user-cert.pem. Should that be necessary? (or am I missing something, the README.md is a bit thin) :)

~tommy

**Comment by ekohl** [comment]
Do you happen to have a line number where it went wrong?

Other than that I'm surprised you have to include apache and those modules since we include what we need. If we don't, that's a bug.

For the README expansion see https://github.com/Katello/puppet-pulp/pull/242.

**Comment by TJM** [comment]
@ekohl - Admittedly that part of the profile was 'inherited' config. It is probably not necessary. I will try removing it. It doesn't really give a line number with the error, but it works fine if I change the yaml key (such that `profile::pulp::rpmrepos` becomes undefined)

I even tried shortening the yaml to:

```
profile::pulp::rpmrepos:
  pulp-2-el7-x86_64:
    display_name: Pulp 2 Production Releases
    feed: https://repos.fedorapeople.org/repos/pulp/pulp/stable/2/7/x86_64/
    relative_url: pulp/stable/2/7/x86_64/
    gpg_key: https://repos.fedorapeople.org/repos/pulp/pulp/GPG-RPM-KEY-pulp-2
```

Still getting:

```
[root@mbi-pulp-01 ~]# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for mbi-pulp-01.utmb.lan
Info: Applying configuration version '4de03acbb3fc11e7ecfefea8cf32f1a339105fbd'
Error: Failed to apply catalog: undefined method `each' for nil:NilClass
[root@mbi-pulp-01 ~]#
```

I also updated my pulp profile recently to include a few more things, one of which trusts the CA cert at the system level, which I read might be an issue in other issues.

```
class profile::pulp (
  $rpmrepos = {},
  $rpmrepos_defaults = {},
  $ca_cert = 'file:///etc/puppetlabs/puppet/ssl/certs/ca.pem'
) {

  # LVM: DataDisk Mounts - please see hieradata/role/pulp.yaml
  include ::lvm

  #  include ::repos::pulp2
  include ::pulp::repo::upstream

  include ::pulp
  include ::pulp::admin

  include ::ca_cert

  # Populate RPM-GPG-KEY files
  file {'/var/lib/pulp/static/rpm-gpg':
    ensure  => 'directory',
    owner   => 'apache',
    group   => 'apache',
    source  => "puppet:///modules/${module_name}/pulp/rpm-gpg",
    recurse => true,
  }

  # Trust CA Cert
  ca_cert::ca {'PulpCA':
    ensure => 'trusted',
    source => $ca_cert
  }

  # RPM Repos
  create_resources('pulp_rpmrepo', $rpmrepos, $rpmrepos_defaults)

  # Ordering
  Class['lvm'] -> Class['pulp'] -> File['/var/lib/pulp/static/rpm-gpg'] -> Ca_cert::Ca <| |> -> Pulp_rpmrepo <| |> -> Pulp_schedule <| |>

  # Firewall
  firewall { '100 INPUT allow http(s) from all':
    dport  => [ '80', '443' ],
    proto  => 'tcp',
    action => 'accept',
    chain  => 'INPUT',
  }

  firewall { '100 INPUT allow http(s) from all IPv6':
    dport    => [ '80', '443' ],
    proto    => 'tcp',
    action   => 'accept',
    chain    => 'INPUT',
    provider => 'ip6tables',
  }

  firewall { '200 OUTPUT allow http(s) to all':
    dport  => [ '80', '443' ],
    proto  => 'tcp',
    action => 'accept',
    chain  => 'INPUT',
  }

  firewall { '200 OUTPUT allow http(s) to all IPv6':
    dport    => [ '80', '443' ],
    proto    => 'tcp',
    action   => 'accept',
    chain    => 'INPUT',
    provider => 'ip6tables',
  }

  # firewall { '200 OUTPUT allow pulp/qpid ports from all':
  #   dport  => '5672',
  #   proto  => 'tcp',
  #   action => 'accept',
  #   chain  => 'INPUT',
  # }
}
```
